# SPDX-License-Identifier: GPL-2.0

baikal_vdu_drm-y +=	baikal_vdu_plane.o \
			baikal_vdu_crtc.o \
			baikal_vdu_drv.o

obj-$(CONFIG_DRM_BAIKAL_VDU) += baikal_vdu_drm.o
obj-$(CONFIG_DRM_BAIKAL_HDMI) += baikal-hdmi.o
