# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_BAIKAL) += bm-dbm.dtb
dtb-$(CONFIG_ARCH_BAIKAL) += bm-mbm10.dtb
dtb-$(CONFIG_ARCH_BAIKAL) += bm-mbm20.dtb
dtb-$(CONFIG_ARCH_BAIKAL) += bm-qemu.dtb
dtb-$(CONFIG_ARCH_BAIKAL) += bm-mitx.dtb
dtb-$(CONFIG_ARCH_BAIKAL) += bm-mitx-d.dtb
dtb-$(CONFIG_ARCH_BAIKAL) += bm-mitx-d-lvds.dtb
dtb-$(CONFIG_ARCH_BAIKAL) += bm-e107.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
