# SPDX-License-Identifier: GPL-2.0
#
# Baikal-M device tree Makefile
#

dtb-$(CONFIG_ARCH_BAIKAL) += bm-bfkm.dtb
dtb-$(CONFIG_ARCH_BAIKAL) += bm-mitx.dtb
dtb-$(CONFIG_ARCH_BAIKAL) += bm-qemu.dtb

#always		:= $(dtb-y)
#subdir-y	:= $(dts-dirs)
#clean-files	:= *.dtb
