// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (C) 2025, Baikal Electronics, JSC
 */

#ifndef __BAIKAL_SMC_H
#define __BAIKAL_SMC_H

#include <linux/arm-smccc.h>

#define BAIKALL_SIP_SMC_FAST_CALL_VAL(func_num) \
	ARM_SMCCC_CALL_VAL(ARM_SMCCC_FAST_CALL, ARM_SMCCC_SMC_64, \
	ARM_SMCCC_OWNER_SIP, (func_num))
	
#define BAIKAL_SMC_CMU_CMD		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0000)
#define BAIKAL_SMC_PVT_CMD		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0001)
#define BAIKAL_SMC_FLASH_WRITE		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0002)
#define BAIKAL_SMC_FLASH_READ		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0003)
#define BAIKAL_SMC_FLASH_ERASE		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0004)
#define BAIKAL_SMC_FLASH_PUSH		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0005)
#define BAIKAL_SMC_FLASH_PULL		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0006)
#define BAIKAL_SMC_FLASH_POSITION	BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0007)
#define BAIKAL_SMC_FLASH_INIT		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0008)
#define BAIKAL_SMC_FLASH_LOCK		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0009)
#define BAIKAL_SMC_VDU_UPDATE		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0100)
#define BAIKAL_SMC_SCP_LOG_DISABLE	BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0200)
#define BAIKAL_SMC_SCP_LOG_ENABLE	BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0201)
#define BAIKAL_SMC_EFUSE_GET_LOT	BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0202)
#define BAIKAL_SMC_EFUSE_GET_SERIAL	BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0203)
#define BAIKAL_SMC_EFUSE_GET_MAC	BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0204)
#define BAIKAL_SMC_EFUSE_GET_BINNING	BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0205)
#define BAIKAL_SMC_VDEC_SMMU_SET_CACHE	BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0300)
#define BAIKAL_SMC_VDEC_SMMU_GET_CACHE	BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0301)
#define BAIKAL_SMC_CLK_ROUND		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0400)
#define BAIKAL_SMC_CLK_SET		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0401)
#define BAIKAL_SMC_CLK_GET		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0402)
#define BAIKAL_SMC_CLK_ENABLE		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0403)
#define BAIKAL_SMC_CLK_DISABLE		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0404)
#define BAIKAL_SMC_CLK_IS_ENABLED	BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0405)
#define BAIKAL_SMC_GMAC_DIV2_ENABLE	BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0500)
#define BAIKAL_SMC_GMAC_DIV2_DISABLE	BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0501)
#define BAIKAL_SMC_LSP_MUX		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0600)
#define BAIKAL_SMC_RST_SET		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0700)
#define BAIKAL_SMC_RST_CLR		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0701)
#define BAIKAL_SMC_PM			BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0800)
#define BAIKAL_SMC_WDT			BAIKALL_SIP_SMC_FAST_CALL_VAL(0x0900)
#define BAIKAL_SMC_THROTTLE		BAIKALL_SIP_SMC_FAST_CALL_VAL(0x1000)

#endif
